stages:
  - test
  - sonar
  - deploy

Sonar-Analyze:
  stage: sonar
  image:
    name: hub.iquantex.com/base/sonar-scanner-cli:latest
    entrypoint: [""]
  variables:
    #SONAR_HOST_URL: "https://sonar.bj.iquantex.com"
    SONAR_USER_HOME: "${CI_PROJECT_DIR}/.sonar"
    GIT_DEPTH: "0"
  cache:
    key: "${CI_PROJECT_NAME}-sonar"
    paths:
      - .sonar/cache
  script:
    - sonar-scanner -Dsonar.host.url=https://sonar.bj.iquantex.com -Dsonar.qualitygate.wait=false -Dsonar.projectKey=${CI_PROJECT_NAME} -Dsonar.sources=./turing_models
  only:
    - master
    - develop
  tags:
    - sigma-dev

Sync_Latest_Models:
  stage: deploy
  variables:
    # 无需拉取源代码.
    GIT_STRATEGY: none
  image: hub.iquantex.com/base/node:12-alpine-with-tools
  script:
    # 在操作前生成git凭证,凭证使用gitlab deploy token定义在项目Settings CI变量中.
    - cat "${GIT_CREDENT}" > ~/.git-credentials
    # 拉取最新master分支代码.
    - cd /home/shared/common && git pull
  after_script:
    # 清除git凭证.
    - rm -f ~/.git-credentials
  only:
    - master
  tags:
    - turing-ide
  retry:
    max: 2