stages:
  - deploy

Sync_To_Common:
  stage: deploy
  image: hub.iquantex.com/base/toolbox:latest
  before_script:
    - cat "${KUBE_PASS_CONFIG}" > kubeconfig
    - cat "${SYNC_JOB}" > sync.yaml
  script:
    - export KUBECONFIG=kubeconfig
    - kubectl create -f sync.yaml
  after_script:
    - kubectl delete -f sync.yaml
  rules:
    - if: '$CI_COMMIT_BRANCH == "develop" && $KUBE_PASS_CONFIG'
  tags:
    - dev

# 增加流水线工作流判断
workflow:
  rules:
    # 匹配项目groups为turing才创建流水线
    - if: '$CI_PROJECT_NAMESPACE == "turing"'
    # 如果URL包含cicc则不创建流水线动作
    - if: '$CI_PROJECT_URL =~ /cicc/'
      when: never
