stages:
  - test
  - sonar
  - deploy


Sync_Latest_Models:
  stage: deploy
  variables:
    # 无需拉取源代码.
    GIT_STRATEGY: none
  image: hub.iquantex.com/base/node:12-alpine-with-tools
  script:
    # 在操作前生成git凭证,凭证使用gitlab deploy token定义在项目Settings CI变量中.
    - cat "${GIT_CREDENT}" > ~/.git-credentials
    # 拉取最新master分支代码.
    - cd /home/shared/common && git pull
  after_script:
    # 清除git凭证.
    - rm -f ~/.git-credentials
  only:
    - master
  tags:
    - turing-ide


code_unit_test:      # 定义一个任务,名字可以任意,但不能使用内置关键字.
  stage: test        # 表明是属于哪一阶段的任务，要与开头的stages一一对应
  script:            # 执行的动作,这里指定动作为执行命令
    - npm run test   # 执行的具体命令,可以添加多行,按顺序从上到下执行每一行
    - mvn test
  only:
    - develop         # 分支或者tag选择,这里表示这个任务阶段仅仅对master分支生效
    - /^feat.*/      # 也可以使用正则表达式匹配
  tags:
    - phx-dev             # 编译机选择标签.

sonar-analyze:
  stage: sonar
  image: hub.iquantex.com/base/sonar-scanner:4.2.0
  script:
    - sonar-scanner -Dsonar.host.url=https://sonar.bj.iquantex.com -Dsonar.qualitygate.wait=false -Dsonar.projectKey=${CI_PROJECT_NAME} -Dsonar.sources=./turing_models  # 自行修改需要分析的源代码目录
  only:
    - develop
  tags:
    - phx-dev
